module.exports = {
	'gh60-ansi': 'GH60 (ANSI)',
	'gh60satan-ansi': 'GH60 Satan (ANSI)',
	'alps64-aek': 'Alps64 (AEK)',
	'minivan-std': 'MiniVan (Standard)',
	'minivan-arrow': 'MiniVan (Arrow)',
	'1up-rgb-custom-pcb-full-map': '1Up RGB Custom PCB (Full)',
	'1up-rgb-custom-pcb-standard-map': '1Up RGB Custom PCB (Standard)',
    '1up-rgb-hse-standard': '1Up RGB HSE PCB (Standard)',
	'1up-sweet16': '1Up Sweet16',
	's60x-rgb-ansi': 'S60-X RGB (ANSI)',
	's60x-rgb-iso': 'S60-X RGB (ISO)',
	's60x-rgb-generic': 'S60-X RGB (Generic)',
	'planck': 'Planck',
	'jd45-default': 'JD45',
	'bantam-pcb': 'Bantam44 (PCB)',
	'alps44': 'Alps44',
	'miuni32-rgb-standard': 'Miuni32 RGB (Standard)',
    'treasure-type9-default': 'Treasure Macropad Type-9',
    'zlant-default': 'Zlant'
};
